
.PHONY: task1 task2 task3

task1:
	echo "Compiling task 1"
	gcc -O0 -g -o task1 task1.c
	./task1 hello world HH@@H """"""DDD CS392 olleh dlrow H@@HH DDD"""""" 293SC

task2:
	echo "Compiling task 2"
	gcc -O0 -g -o task2 task2.c
	./task2

task3:
	echo "Compiling task 3"
	gcc -O0 -g -o task3 task3.c
	./task3
